### ISSUE TITLE
Benchmark results

### ISSUE THREAD

**Issue by zamazan4ik** [ispringteam/FastSignals#6]
Hello!
Can you post please benchmark results between FastSignals and Boost.Signal2? 
Thank you.

**Comment by alexey-malov** [comment]
Benchmarks are available in a separate repository:
https://github.com/ispringteam/FastSignalsBenchmark

FastSignals are approximately 85-120% faster than Boost.Signals2.

**Comment by zamazan4ik** [comment]
Thank you!
